server {
    listen 80;
    listen [::]:80;
    server_name landing.nexofitness.cl;

    return 301 https://nexofitness.cl$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name landing.nexofitness.cl;

    ssl_certificate /etc/ssl/cloudflare/nexofitness.cl.pem;
    ssl_certificate_key /etc/ssl/cloudflare/nexofitness.cl.key;
    return 301 https://nexofitness.cl$request_uri;
}
