import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#020617',
  },
  container: {
    padding: 20,
    gap: 16,
  },
  hero: {
    paddingTop: 8,
    gap: 10,
  },
  kicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  title: {
    color: '#f8fafc',
    fontSize: 30,
    fontWeight: '800',
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#0f172a',
  },
  pillText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '700',
  },
  tabBar: {
    marginTop: 2,
  },
  tabBarContent: {
    gap: 10,
    paddingRight: 4,
  },
  tabButton: {
    minWidth: 112,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#0b1220',
    borderWidth: 1,
    borderColor: '#1e293b',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  tabButtonActive: {
    backgroundColor: '#0f2131',
  },
  tabButtonText: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '700',
  },
  tabButtonTextActive: {
    color: '#f8fafc',
  },
  tabBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: '#08111f',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  tabBadgeText: {
    color: '#67e8f9',
    fontSize: 11,
    fontWeight: '800',
  },
  tabIntroCard: {
    backgroundColor: '#07101d',
    borderColor: '#122033',
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    gap: 6,
  },
  tabIntroTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  tabIntroText: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 21,
  },
  routeBar: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  routeHeaderBody: {
    flex: 1,
    gap: 4,
  },
  card: {
    backgroundColor: '#0b1220',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 24,
    padding: 18,
    gap: 12,
  },
  sectionTitle: {
    color: '#f8fafc',
    fontSize: 19,
    fontWeight: '700',
  },
  sectionHint: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 21,
  },
  input: {
    backgroundColor: '#111827',
    borderColor: '#1f2937',
    borderWidth: 1,
    borderRadius: 16,
    color: '#f8fafc',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  button: {
    minHeight: 48,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    flex: 1,
  },
  buttonSecondary: {
    backgroundColor: '#111827',
    borderWidth: 1,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  inlineActionButton: {
    minHeight: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  inlineActionButtonSecondary: {
    backgroundColor: '#111827',
    borderWidth: 1,
  },
  inlineActionText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  buttonSecondaryText: {
    color: '#cbd5e1',
  },
  statusBlock: {
    backgroundColor: '#0f172a',
    borderRadius: 16,
    padding: 14,
    gap: 6,
  },
  statusLabel: {
    color: '#67e8f9',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  statusText: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 20,
  },
  metricRow: {
    flexDirection: 'row',
    gap: 12,
  },
  metric: {
    flex: 1,
    backgroundColor: '#111827',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  metricLabel: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  brandingPanel: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    gap: 8,
    backgroundColor: '#08111f',
  },
  inlinePanel: {
    backgroundColor: '#0f172a',
    borderRadius: 18,
    padding: 16,
    gap: 6,
  },
  primaryValue: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '700',
  },
  secondaryValue: {
    color: '#94a3b8',
    fontSize: 14,
  },
  description: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 21,
  },
  listBlock: {
    gap: 10,
  },
  filterGroup: {
    gap: 8,
  },
  filterLabel: {
    color: '#67e8f9',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  filterRow: {
    gap: 8,
    paddingRight: 4,
  },
  filterChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#08111f',
    borderWidth: 1,
    borderColor: '#334155',
  },
  filterChipActive: {
    backgroundColor: '#0f2131',
  },
  filterChipText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '700',
  },
  filterChipTextActive: {
    color: '#f8fafc',
  },
  listTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  listRow: {
    backgroundColor: '#0f172a',
    borderRadius: 16,
    padding: 14,
    gap: 4,
  },
  scheduleCard: {
    backgroundColor: '#0f172a',
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  detailPanel: {
    backgroundColor: '#08111f',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1e293b',
    padding: 14,
    gap: 10,
  },
  detailRow: {
    gap: 4,
  },
  detailLabel: {
    color: '#67e8f9',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  listRowTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '600',
  },
  listRowMeta: {
    color: '#94a3b8',
    fontSize: 13,
  },
  paymentAmount: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
  },
  codeBlock: {
    backgroundColor: '#020617',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  codeLabel: {
    color: '#67e8f9',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  codeText: {
    color: '#e2e8f0',
    fontSize: 13,
    lineHeight: 20,
  },
  planGrid: {
    gap: 10,
  },
  planCard: {
    backgroundColor: '#111827',
    borderColor: '#1f2937',
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    gap: 8,
  },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  stateBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#08111f',
  },
  stateBadgeMuted: {
    borderColor: '#334155',
  },
  stateBadgeText: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  planTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
  },
  planBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  planBadgeText: {
    color: '#082f49',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  planPrice: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
  },
  planMeta: {
    color: '#67e8f9',
    fontSize: 13,
    fontWeight: '600',
  },
  planDescription: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 20,
  },
  listItem: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 22,
  },
  emptyText: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 21,
  },
});
